Hotfix/70259368 Agregando pruebas unitarias
EntrevistadorInteligente/generador-feedback pull request #19
Opened 2024-07-11 00:54 UTC by Kirenai

## TL;DR

Closes # 

## 📑 Description

Se agrega pruebas unitarias

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-07-11 02:00 UTC, JamiltonQuintero requested changes
Por aqui dejo un ejemplo por si algo 
https://stackoverflow.com/questions/36253040/example-of-mockitos-argumentcaptor

// Create a mock of the OtherClass
OtherClass other = mock(OtherClass.class);

// Run the foo method with the mock
new A().foo(other);

// Capture the argument of the doSomething function
ArgumentCaptor<SomeData> captor = ArgumentCaptor.forClass(SomeData.class);
verify(other, times(1)).doSomething(captor.capture());

// Assert the argument
SomeData actual = captor.getValue();
assertEquals("Some inner data", actual.innerData);

2024-07-11 02:00 UTC, JamiltonQuintero commented on src/test/java/com/entrevistador/generadorfeedback/infrastructure/adapter/dao/FeedbackDBDaoTest.java
> +        FeedbackEntity feedbackEntity = FeedbackMock.getInstance().getFeedbackEntity();
Señor Kire podriamos empezar mockear con datos probablemente mas realos las entidades asi los flujos que se den hacen validaciones mas reales y podemos ahcer asserts contra valores. Cosa que si en un futuro algun dev llega a cambair algo los test se rompan y como no estamos haciendo asserts aqui si algo llegase a cambiar probablemente nada se rompa (Aplicaria para todos los test) y si es un voy podriamos usar argument captor en alguna de las llamadas a los metodos

2024-07-12 05:39 UTC, Kirenai commented
Va a ser complicado el uso de ArgumentCaptor en los tests.

2024-07-12 06:08 UTC, Kirenai commented
O tal vez capte mal la idea y se refiere al cambio en el último commit.

2024-07-12 17:05 UTC, JamiltonQuintero commented on src/test/java/com/entrevistador/generadorfeedback/infrastructure/adapter/dao/FeedbackDBDaoTest.java
> +        FeedbackEntity feedbackEntity = FeedbackMock.getInstance().getFeedbackEntity();
No pasa nada alli lo revisamos a detalle mas luego

2024-07-12 17:05 UTC, JamiltonQuintero approved these changes

2024-07-12 17:05 UTC, merged