Develop
EntrevistadorInteligente/generador-feedback pull request #2
Opened 2024-01-08 11:47 UTC by JamiltonQuintero

2024-01-08 23:33 UTC, svg153 requested changes

2024-01-08 23:33 UTC, svg153 commented on .gitignore
> +HELP.md
- [ ] Añadir teen estos paths
https://github.com/github/gitignore/blob/main/Maven.gitignore

2024-01-15 11:03 UTC, JamiltonQuintero commented on .gitignore
> +HELP.md
Resuelto

2024-01-15 16:10 UTC, svg153 submitted a review, later dismissed

2024-04-19 16:12 UTC, svg153 approved these changes, later dismissed

2024-06-02 21:50 UTC, closed without merging